### DataFrame

A DataFrame is a two-dimensional table in Pandas that stores data in rows and columns, similar to an Excel spreadsheet.

In [6]:
import pandas as pd
df = pd.DataFrame([11,22,33])
print(df)

    0
0  11
1  22
2  33

In [5]:
import pandas as pd
df = pd.DataFrame([11,22,33],columns=['col_name'])
print(df)

   col_name
0        11
1        22
2        33

In [7]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [11]:
import pandas as pd

data = {
    'Name': ['Yangla', 'Sonam', 'Gyajola'],
    'Age': [24, 27, 22],
    'Salary': [20000, 30000, 40000]
}

df = pd.DataFrame(data)

print(df)

      Name  Age  Salary
0   Yangla   24   20000
1    Sonam   27   30000
2  Gyajola   22   40000

In [14]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

### Basic DataFrame Understanding

In [16]:
df.head(1)   #top rows

     Name  Age  Salary
0  Yangla   24   20000

In [17]:
df.tail(2)  #last rows

      Name  Age  Salary
1    Sonam   27   30000
2  Gyajola   22   40000

In [19]:
df.shape  # rows and column total count

(3, 3)

In [20]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='object')

In [30]:
df1 = df.rename(columns={'Salary':'Monthly_salary'})

In [27]:
df.rename(columns={'Salary':'Monthly_salary'}, inplace=True)

In [28]:
df

      Name  Age  Monthly_salary
0   Yangla   24           20000
1    Sonam   27           30000
2  Gyajola   22           40000

In [26]:
df1

      Name  Age  Monthly_salary
0   Yangla   24           20000
1    Sonam   27           30000
2  Gyajola   22           40000

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            3 non-null      object
 1   Age             3 non-null      int64
 2   Monthly_salary  3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [32]:
df.describe()

             Age  Monthly_salary
count   3.000000             3.0
mean   24.333333         30000.0
std     2.516611         10000.0
min    22.000000         20000.0
25%    23.000000         25000.0
50%    24.000000         30000.0
75%    25.500000         35000.0
max    27.000000         40000.0


### Save and Load from csv

In [40]:
df.to_csv ('test_data.csv')

In [42]:
df.to_csv("test_data.csv", index=False)

In [47]:
from google.colab import files
files.download('test_data.csv')  #save in excel

In [46]:
load_df = pd.read_csv('test_data.csv')
load_df

      Name  Age  Monthly_salary
0   Yangla   24           20000
1    Sonam   27           30000
2  Gyajola   22           40000

### Rows and columns- selection

In [48]:
df

      Name  Age  Monthly_salary
0   Yangla   24           20000
1    Sonam   27           30000
2  Gyajola   22           40000

In [54]:
df[['Name']]  #single column

      Name
0   Yangla
1    Sonam
2  Gyajola

In [53]:
df[['Name', 'Monthly_salary']] #double column

      Name  Monthly_salary
0   Yangla           20000
1    Sonam           30000
2  Gyajola           40000

In [56]:
#loc- Label based Index
df.loc[df.Name=='Yangla'] #select single row

     Name  Age  Monthly_salary
0  Yangla   24           20000

In [60]:
df.loc[(df.Name=='Yangla') & (df.Monthly_salary>=20000)]

     Name  Age  Monthly_salary
0  Yangla   24           20000

In [62]:
#iloc- index-value based
df.iloc[0]

Name              Yangla
Age                   24
Monthly_salary     20000
Name: 0, dtype: object

In [66]:
df.iloc[0:2]

     Name  Age  Monthly_salary
0  Yangla   24           20000
1   Sonam   27           30000

### Filter DataFrame

In [33]:
import pandas as pd

data = {
    'Name': ['Yangla', 'Sonam', 'Gyajola'],
    'Age': [24, 27, 22],
    'Salary': [20000, 30000, 40000]
}

df = pd.DataFrame(data)
df

      Name  Age  Salary
0   Yangla   24   20000
1    Sonam   27   30000
2  Gyajola   22   40000

In [5]:
df

      Name  Age  Salary
0   Yangla   24   20000
1    Sonam   27   30000
2  Gyajola   22   40000

In [16]:
df['Age'] >= 23

0     True
1     True
2    False
Name: Age, dtype: bool

In [17]:
df_age_filter = df['Age'] >= 23

In [18]:
df_age_filter

0     True
1     True
2    False
Name: Age, dtype: bool

In [23]:
df[(df['Age'] >= 23) & (df['Salary'] >=20000)]

     Name  Age  Salary
0  Yangla   24   20000
1   Sonam   27   30000

In [24]:
df.where(df['Age'] >= 23)

     Name   Age   Salary
0  Yangla  24.0  20000.0
1   Sonam  27.0  30000.0
2     NaN   NaN      NaN

In [26]:
df.where(df['Age'] >= 23,other = 'not eligible')

           Name           Age        Salary
0        Yangla            24         20000
1         Sonam            27         30000
2  not eligible  not eligible  not eligible

### Rows and Columns - operations (Add, Update, Delete)

In [27]:
df

      Name  Age  Salary
0   Yangla   24   20000
1    Sonam   27   30000
2  Gyajola   22   40000

In [29]:
#add new column
df['Team'] = ['CEO', 'HR', 'CTO']
df

      Name  Age  Salary Team
0   Yangla   24   20000  CEO
1    Sonam   27   30000   HR
2  Gyajola   22   40000  CTO

In [32]:
# multiplication operation
df['bonus'] = df['Salary']*0.20
df

      Name  Age  Salary Team   bonus
0   Yangla   24   20000  CEO  4000.0
1    Sonam   27   30000   HR  6000.0
2  Gyajola   22   40000  CTO  8000.0

In [50]:
df['Team'] = ['CEO', 'HR', 'CTO', 'Finance']
df

      Name  Age  Salary    bonus     Team
0   Yangla   24   20000   4000.0      CEO
1    Sonam   27   30000   6000.0       HR
2  Gyajola   22   40000   8000.0      CTO
3   Pasang   48   50000  18000.0  Finance

In [53]:
#Add rows
df.loc[len(df)] = ['Nisha', 52, 60000, 18000, 'Finance']
df

      Name  Age  Salary    bonus     Team
0   Yangla   24   20000   4000.0      CEO
1    Sonam   27   30000   6000.0       HR
2  Gyajola   22   40000   8000.0      CTO
3   Pasang   48   50000  18000.0  Finance
4   Pasang   48   50000  18000.0  Finance
5    Nisha   52   60000  18000.0  Finance
6    Nisha   52   60000  18000.0  Finance

In [48]:
df()

      Name  Age  Salary    bonus
0   Yangla   24   20000   4000.0
1    Sonam   27   30000   6000.0
2  Gyajola   22   40000   8000.0
3   Pasang   48   50000  18000.0

In [101]:
df.drop(5)

     Name  Salary
0  Yangla   25000

In [60]:
len(df)

7

### Update Value - Using index name

In [61]:
df.loc[0,'Salary'] = 25000
df

      Name  Age  Salary    bonus     Team
0   Yangla   24   25000   4000.0      CEO
1    Sonam   27   30000   6000.0       HR
2  Gyajola   22   40000   8000.0      CTO
3   Pasang   48   50000  18000.0  Finance
4   Pasang   48   50000  18000.0  Finance
5    Nisha   52   60000  18000.0  Finance
6    Nisha   52   60000  18000.0  Finance

Update value using column value

In [63]:
df.loc[df.Name=='Yangla','Salary'] = 25000
df

      Name  Age  Salary    bonus     Team
0   Yangla   24   25000   4000.0      CEO
1    Sonam   27   30000   6000.0       HR
2  Gyajola   22   40000   8000.0      CTO
3   Pasang   48   50000  18000.0  Finance
4   Pasang   48   50000  18000.0  Finance
5    Nisha   52   60000  18000.0  Finance
6    Nisha   52   60000  18000.0  Finance

### Delete value - row and column values

In [87]:
 #drop row, axis =0
df.drop(df[df.Name == 'Pasang'].index)

      Name  Age  Salary
0   Yangla   24   25000
1    Sonam   27   30000
2  Gyajola   22   40000
5    Nisha   52   60000
6    Nisha   52   60000

In [89]:
df.drop('Age', axis=1, inplace= True)
df

      Name  Salary
0   Yangla   25000
1    Sonam   30000
2  Gyajola   40000
5    Nisha   60000
6    Nisha   60000

In [115]:
df = df.drop(df.index[2:5])
df

     Name  Salary
0  Yangla   25000

In [2]:
import pandas as pd

data = {
    'Name': ['Yangla', 'Sonam', 'Gyajola'],
    'Age': [24, 27, 22],
    'Salary': [20000, 30000, 40000]
}

df = pd.DataFrame(data)
df

      Name  Age  Salary
0   Yangla   24   20000
1    Sonam   27   30000
2  Gyajola   22   40000

In [3]:
df.drop(1,axis=0) #index name row delete

      Name  Age  Salary
0   Yangla   24   20000
2  Gyajola   22   40000

In [7]:
# sort values
df.sort_values('Salary') # ascending order by default

      Name  Age  Salary
0   Yangla   24   20000
1    Sonam   27   30000
2  Gyajola   22   40000

In [8]:
#sort values (descending order)
df.sort_values('Salary', ascending= False)

      Name  Age  Salary
2  Gyajola   22   40000
1    Sonam   27   30000
0   Yangla   24   20000

### Wokring with dates values

In [12]:
df["Date"] = ["2026-03-10", "2026-01-15", "2026-02-20"]
df

      Name  Age  Salary        Date
0   Yangla   24   20000  2026-03-10
1    Sonam   27   30000  2026-01-15
2  Gyajola   22   40000  2026-02-20

In [14]:
df['Date'] = pd.to_datetime(df['Date'])

In [15]:
df['Date'].dtype

dtype('<M8[ns]')